CREATE TABLE Cars (
CarID NUMBER,
RegID NUMBER,
OwnerID NUMBER,
SpaceID NUMBER,
OffersID NUMBER,
ContractID NUMBER,
PRIMARY KEY (CarID),
CONSTRAINT FK_RegID FOREIGN KEY (RegID)
REFERENCES Cars(RegID),
CONSTRAINT FK_OwnerID FOREIGN KEY (OwnerID)
REFERENCES Users(UserID),
CONSTRAINT FK_OffersID FOREIGN KEY (OfferID)
REFERENCES Offers(OfferID),
CONSTRAINT FK_ContractID FOREIGN KEY (ContractID)
REFERENCES Contracts(ContractID)
);

CREATE TABLE CarReges(
RegID NUMBER,
Make VARCHAR,
Model VARCHAR,
Year INT,
MSRP FLOAT,
CarID NUMBER,
PRIMARY KEY (CarID),
CONSTRAINT FK_Car FOREIGN KEY (CarID)
REFERENCES Cars(CarID)
);

CREATE TABLE Contracts (
ContractID NUMBER,
CarID NUMBER,
SoldOffer FLOAT,
Balance FLOAT,
Terms INT,
PRIMARY KEY (ContractID),
CONSTRAINT FK_Car FOREIGN KEY (CarID)
REFERENCES Cars(CarID)
);

CREATE TABLE Offers (
OfferID NUMBER,
Amount FLOAT,
Term INT,
APR FLOAT,
OffereeID NUMBER,
ProductID NUMBER,
PRIMARY KEY (OfferID,ProductID),
CONSTRAINT FK_Offeree FOREIGN KEY (OffereeID)
REFERENCES Users,
CONSTRAINT FK_Product FOREIGN KEY (ProductID)
REFERENCES Cars(CarID)
);

CREATE TABLE Payments (
PaymentID NUMBER,
ContractID NUMBER,
Amount FLOAT,
PayDate DATE,
PRIMARY KEY (PaymentID,ContractID),
CONSTRAINT FK_Contract FOREIGN KEY (ContractID)
REFERENCES Contracts(ContractID)
);

CREATE TABLE Users (
UserDriversID NUMBER,
Password VARCHAR,
Type BOOLEAN,
PRIMARY KEY (UserDriversID)
);

